
module.exports = {
  CONNECTING: 'connecting',
  CONNECTED: 'connect',
  DISCONNECTED: 'disconnect',
  RECONNECTING: 'reconnecting',
  RECONNECTED: 'reconnected',
  CONNECTION_ERROR: 'connect_error',
  CONNECTION_TIMEOUT: 'connect_timeout',
  PING: 'ping',
  PONG: 'pong',
  PACKET_SENT: 'packet sent',
  PACKET_RECEIVED: 'packet received',
  LOGIN_SUCCESS: 'login success',
  LOGIN_FAILED: 'login failed',
  LOG: 'log',
  INTERNAL_ERROR: 'internal error',
  JOINED_GROUP: 'joined group',
  LEFT_GROUP: 'left group',
  READY: 'ready',
  PERMISSIONS_FAILED: 'permissions failed',
  PRIVATE_MESSAGE_ACCEPT_RESPONSE: 'private message accept response',
  RECONNECT_FAILED: 'reconnect failed',
  ERROR: 'error',

  STAGE_CLIENT_READY: 'stage client ready',
  STAGE_CLIENT_MUTED: 'stage client muted',
  STAGE_CLIENT_UNMUTED: 'stage client unmuted',
  STAGE_CLIENT_PAUSED: 'stage client paused',
  STAGE_CLIENT_UNPAUSED: 'stage client unpaused',
  STAGE_CLIENT_BROADCAST_ENDED: 'stage client broadcast ended',
  STAGE_CLIENT_CONNECTED: 'stage client connected',
  STAGE_CLIENT_DISCONNECTED: 'stage client disconnected',
  STAGE_CLIENT_STOPPED: 'stage client stopped',
  STAGE_CLIENT_VIEWER_COUNT_CHANGED: 'stage client viewer count changed',
  STAGE_CLIENT_ERROR: 'stage client error'
};
