
module.exports = {
  CONNECTING: 'connecting',
  CONNECTED: 'connect',
  DISCONNECTED: 'disconnect',
  RECONNECTING: 'reconnecting',
  RECONNECTED: 'reconnected',
  CONNECTION_ERROR: 'connect_error',
  CONNECTION_TIMEOUT: 'connect_timeout',
  GROUP_MESSAGE: 'group message',
  NOTIFICATION_RECEIVED: 'notification received',
  PING: 'ping',
  PONG: 'pong',
  PRIVATE_MESSAGE: 'private message',
  PACKET_SENT: 'packet sent',
  PACKET_RECEIVED: 'packet received',
  LOGIN_SUCCESS: 'login success',
  LOGIN_FAILED: 'login failed',
  LOG: 'log',
  INTERNAL_ERROR: 'internal error',
  JOINED_GROUP: 'joined group',
  LEFT_GROUP: 'left group',
  READY: 'ready',
  PERMISSIONS_FAILED: 'permissions failed',
  PRIVATE_MESSAGE_ACCEPT_RESPONSE: 'private message accept response',
  RECONNECT_FAILED: 'reconnect failed',
  ERROR: 'error'
};
