module.exports = {
  NOT_SPECIFIED: 0,
  BUSINESS: 8,
  EDUCATION: 10,
  ENTERTAINMENT: 26,
  GAMING: 12,
  LIFESTYLE: 13,
  MUSIC: 14,
  NEWS_AND_POLITICS: 15,
  PHOTOGRAPHY: 16,
  SCIENCE_AND_TECH: 25,
  SOCIAL_AND_PEOPLE: 17,
  SPORTS: 19,
  TRAVEL_AND_LOCAL: 18
};
