module.exports = {
  ACHIEVEMENT: 'achievement',
  ACHIEVEMENT_CATEGORY_LIST: 'achievement category list',
  ACHIEVEMENT_GROUP_LIST: 'achievement group list',
  ACHIEVEMENT_SUBSCRIBER_LIST: 'achievement subscriber list',

  CHARM_LIST: 'charm list',
  CHARM_SUBSCRIBER_ACTIVE_LIST: 'charm subscriber active list',
  CHARM_SUBSCRIBER_DELETE: 'charm subscriber delete',
  CHARM_SUBSCRIBER_EXPIRED_LIST: 'charm subscriber expired list',
  CHARM_SUBSCRIBER_SET_SELECTED: 'charm subscriber set selected',
  CHARM_SUBSCRIBER_STATISTICS: 'charm subscriber statistics',
  CHARM_SUBSCRIBER_SUMMARY_LIST: 'charm subscriber summary list',

  GROUP_AUDIO_BROADCAST: 'group audio broadcast',
  GROUP_AUDIO_BROADCAST_DISCONNECT: 'group audio broadcast disconnect',
  GROUP_AUDIO_BROADCAST_UPDATE: 'group audio broadcast update',
  GROUP_AUDIO_CONSUME: 'group audio consume',
  GROUP_AUDIO_REQUEST_ADD: 'group audio request add',
  GROUP_AUDIO_REQUEST_CLEAR: 'group audio request clear',
  GROUP_AUDIO_REQUEST_DELETE: 'group audio request delete',
  GROUP_AUDIO_REQUEST_LIST: 'group audio request list',
  GROUP_AUDIO_SLOT_LIST: 'group audio slot list',
  GROUP_AUDIO_SLOT_UPDATE: 'group audio slot update',
  GROUP_AUDIO_UPDATE: 'group audio update',
  GROUP_CREATE: 'group create',
  GROUP_EVENT: 'group event',
  GROUP_EVENT_CREATE: 'group event create',
  GROUP_EVENT_DELETE: 'group event delete',
  GROUP_EVENT_LIST: 'group event list',
  GROUP_EVENT_UPDATE: 'group event update',
  GROUP_MEMBER: 'group member',
  GROUP_MEMBER_ADD: 'group member add',
  GROUP_MEMBER_DELETE: 'group member delete',
  GROUP_MEMBER_PRIVILEGED_LIST: 'group member privileged list',
  GROUP_MEMBER_REGULAR_LIST: 'group member regular list',
  GROUP_MEMBER_BANNED_LIST: 'group member banned list',
  GROUP_MEMBER_UPDATE: 'group member update',
  GROUP_PROFILE: 'group profile',
  GROUP_PROFILE_UPDATE: 'group profile update',
  GROUP_RECOMMENDATION_LIST: 'group recommendation list',
  GROUP_STATS: 'group stats',

  MESSAGE_CONVERSATION_LIST: 'message conversation list',
  MESSAGE_GROUP_HISTORY_LIST: 'message group history list',
  MESSAGE_GROUP_SUBSCRIBE: 'message group subscribe',
  MESSAGE_GROUP_UNSUBSCRIBE: 'message group unsubscribe',
  MESSAGE_PRIVATE_HISTORY_LIST: 'message private history list',
  MESSAGE_PRIVATE_SUBSCRIBE: 'message private subscribe',
  MESSAGE_PRIVATE_UNSUBSCRIBE: 'message private unsubscribe',
  MESSAGE_SEND: 'message send',
  MESSAGE_SETTING: 'message setting',
  MESSAGE_SETTING_UPDATE: 'message setting update',
  MESSAGE_UPDATE: 'message update',
  MESSAGE_UPDATE_LIST: 'message update list',

  METADATA_URL: 'metadata url',
  METADATA_URL_BLACKLIST: 'metadata url blacklist',

  NOTIFICATION_LIST: 'notification list',
  NOTIFICATION_LIST_CLEAR: 'notification list clear',

  SEARCH: 'search',

  SECURITY_LOGIN: 'security login',
  SECURITY_LOGOUT: 'security logout',
  SECURITY_TOKEN_REFRESH: 'security token refresh',

  STAGE_GROUP_ACTIVE_LIST: 'stage group active list',
  STAGE_LIST: 'stage list',

  STORE_CREDIT_BALANCE: 'store credit balance',
  STORE_PRODUCT: 'store product',
  STORE_PRODUCT_PROFILE: 'store product profile',
  STORE_PRODUCT_CREDIT_LIST: 'store product credit list',

  SUBSCRIBER_BLOCK_ADD: 'subscriber block add',
  SUBSCRIBER_BLOCK_DELETE: 'subscriber block delete',
  SUBSCRIBER_BLOCK_LIST: 'subscriber block list',
  SUBSCRIBER_CONTACT_ADD: 'subscriber contact add',
  SUBSCRIBER_CONTACT_DELETE: 'subscriber contact delete',
  SUBSCRIBER_CONTACT_LIST: 'subscriber contact list',
  SUBSCRIBER_GROUP_EVENT_ADD: 'subscriber group event add',
  SUBSCRIBER_GROUP_EVENT_DELETE: 'subscriber group event delete',
  SUBSCRIBER_GROUP_EVENT_LIST: 'subscriber group event list',
  SUBSCRIBER_GROUP_LIST: 'subscriber group list',
  SUBSCRIBER_PRESENCE: 'subscriber presence',
  SUBSCRIBER_PROFILE: 'subscriber profile',
  SUBSCRIBER_PROFILE_UPDATE: 'subscriber profile update',
  SUBSCRIBER_SETTINGS_UPDATE: 'subscriber settings update',

  TIP_ADD: 'tip add',
  TIP_DETAIL: 'tip detail',
  TIP_GROUP_SUBSCRIBE: 'tip group subscribe',
  TIP_LEADERBOARD_GLOBAL: 'tip leaderboard global',
  TIP_LEADERBOARD_GLOBAL_SUMMARY: 'tip leaderboard global summary',
  TIP_LEADERBOARD_GROUP: 'tip leaderboard group',
  TIP_LEADERBOARD_GROUP_SUMMARY: 'tip leaderboard group summary',
  TIP_PRIVATE_SUBSCRIBE: 'tip private subscribe',
  TIP_SUMMARY: 'tip summary',

  TOPIC_PAGE_LAYOUT: 'topic page layout',
  TOPIC_PAGE_RECIPE_LIST: 'topic page recipe list'
};
