
exports.serverEvents = {
  GROUP_AUDIO_COUNT_UPDATE: 'group audio count update',
  GROUP_AUDIO_SLOT_UPDATE: 'group audio slot update',
  GROUP_AUDIO_UPDATE: 'group audio update',
  GROUP_EVENT_CREATE: 'group event create',
  GROUP_EVENT_UPDATE: 'group event update',
  GROUP_MEMBER_ADD: 'group member add',
  GROUP_MEMBER_DELETE: 'group member delete',
  GROUP_MEMBER_UPDATE: 'group member update',
  GROUP_UPDATE: 'group update',
  MESSAGE_SEND: 'message send',
  MESSAGE_UPDATE: 'message update',
  PRESENCE_UPDATE: 'presence update',
  SUBSCRIBER_BLOCK_ADD: 'subscriber block add',
  SUBSCRIBER_BLOCK_DELETE: 'subscriber block delete',
  SUBSCRIBER_CONTACT_ADD: 'subscriber contact add',
  SUBSCRIBER_CONTACT_DELETE: 'subscriber contact delete',
  SUBSCRIBER_GROUP_EVENT_ADD: 'subscriber group event add',
  SUBSCRIBER_GROUP_EVENT_DELETE: 'subscriber group event delete',
  SUBSCRIBER_UPDATE: 'subscriber update',
  TIP_ADD: 'tip add',
  WELCOME: 'welcome'
};

exports.events = {
  CONNECTED: 'connected',
  CONNECTING: 'connecting',
  CONNECTION_ERROR: 'connectError',
  CONNECTION_TIMEOUT: 'connectTimeout',
  DISCONNECTED: 'disconnected',
  ERROR: 'error',
  GROUP_AUDIO_COUNT_UPDATE: 'groupAudioCountUpdate',
  GROUP_AUDIO_SLOT_UPDATE: 'groupAudioSlotUpdate',
  GROUP_AUDIO_UPDATE: 'groupAudioUpdate',
  GROUP_EVENT_CREATE: 'groupEventCreate',
  GROUP_EVENT_UPDATE: 'groupEventUpdate',
  GROUP_MEMBER_ADD: 'groupMemberAdd',
  GROUP_MEMBER_DELETE: 'groupMemberDelete',
  GROUP_MEMBER_UPDATE: 'groupMemberUpdate',
  GROUP_MESSAGE: 'groupMessage',
  GROUP_MESSAGE_UPDATE: 'groupMessageUpdate',
  GROUP_TIP_ADD: 'groupTipAdd',
  GROUP_UPDATE: 'groupUpdate',
  INTERNAL_ERROR: 'internalError',
  JOINED_GROUP: 'joinedGroup',
  LEFT_GROUP: 'leftGroup',
  LOG: 'log',
  LOGIN_FAILED: 'loginFailed',
  LOGIN_SUCCESS: 'loginSuccess',
  NOTIFICATION_RECEIVED: 'notificationReceived',
  PACKET_RECEIVED: 'packetReceived',
  PACKET_SENT: 'packetSent',
  PING: 'ping',
  PONG: 'pong',
  PRESENCE_UPDATE: 'presenceUpdate',
  PRIVATE_MESSAGE: 'privateMessage',
  PRIVATE_MESSAGE_ACCEPT_RESPONSE: 'privateMessageAcceptResponse',
  PRIVATE_MESSAGE_UPDATE: 'privateMessageUpdate',
  PRIVATE_TIP_ADD: 'privateTipAdd',
  READY: 'ready',
  RECONNECTED: 'reconnected',
  RECONNECTING: 'reconnecting',
  RECONNECT_FAILED: 'reconnectFailed',
  STAGE_CLIENT_BROADCAST_END: 'stageClientBroadcastEnd',
  STAGE_CLIENT_CONNECTED: 'stageClientConnected',
  STAGE_CLIENT_CONNECTING: 'stageClientConnecting',
  STAGE_CLIENT_DISCONNECTED: 'stageClientDisconnected',
  STAGE_CLIENT_DURATION_UPDATE: 'stageClientDuration',
  STAGE_CLIENT_ERROR: 'stageClientError',
  STAGE_CLIENT_KICKED: 'stageClientKicked',
  STAGE_CLIENT_MUTED: 'stageClientMuted',
  STAGE_CLIENT_PAUSED: 'stageClientPaused',
  STAGE_CLIENT_READY: 'stageClientReady',
  STAGE_CLIENT_STOPPED: 'stageClientStopped',
  STAGE_CLIENT_UNMUTED: 'stageClientUnmuted',
  STAGE_CLIENT_UNPAUSED: 'stageClientUnpaused',
  STAGE_CLIENT_VIEWER_COUNT_CHANGED: 'stageClientViewerCountChanged',
  SUBSCRIBER_BLOCK_ADD: 'subscriberBlockAdd',
  SUBSCRIBER_BLOCK_DELETE: 'subscriberBlockDelete',
  SUBSCRIBER_CONTACT_ADD: 'subscriberContactAdd',
  SUBSCRIBER_CONTACT_DELETE: 'subscriberContactDelete',
  SUBSCRIBER_GROUP_EVENT_ADD: 'subscriberGroupEventAdd',
  SUBSCRIBER_GROUP_EVENT_DELETE: 'subscriberGroupEventDelete',
  SUBSCRIBER_UPDATE: 'subscriberUpdate',
  WELCOME: 'welcome'
};

exports.messageTypes = {
  GROUP: 'group',
  PRIVATE: 'private'
};

exports.commands = {
  ACHIEVEMENT: 'achievement',
  ACHIEVEMENT_CATEGORY_LIST: 'achievement category list',
  ACHIEVEMENT_GROUP_LIST: 'achievement group list',
  ACHIEVEMENT_SUBSCRIBER_LIST: 'achievement subscriber list',

  CHARM_LIST: 'charm list',
  CHARM_SUBSCRIBER_ACTIVE_LIST: 'charm subscriber active list',
  CHARM_SUBSCRIBER_DELETE: 'charm subscriber delete',
  CHARM_SUBSCRIBER_EXPIRED_LIST: 'charm subscriber expired list',
  CHARM_SUBSCRIBER_SET_SELECTED: 'charm subscriber set selected',
  CHARM_SUBSCRIBER_STATISTICS: 'charm subscriber statistics',
  CHARM_SUBSCRIBER_SUMMARY_LIST: 'charm subscriber summary list',

  GROUP_AUDIO_BROADCAST: 'group audio broadcast',
  GROUP_AUDIO_BROADCAST_DISCONNECT: 'group audio broadcast disconnect',
  GROUP_AUDIO_BROADCAST_UPDATE: 'group audio broadcast update',
  GROUP_AUDIO_CONSUME: 'group audio consume',
  GROUP_AUDIO_SLOT_LIST: 'group audio slot list',
  GROUP_AUDIO_SLOT_UPDATE: 'group audio slot update',
  GROUP_AUDIO_UPDATE: 'group audio update',

  // TODO: Raise Hand support upon client release

  GROUP_CREATE: 'group create',
  GROUP_EVENT: 'group event',
  GROUP_EVENT_CREATE: 'group event create',
  GROUP_EVENT_DELETE: 'group event delete',
  GROUP_EVENT_LIST: 'group event list',
  GROUP_EVENT_UPDATE: 'group event update',
  GROUP_MEMBER_ADD: 'group member add',
  GROUP_MEMBER_DELETE: 'group member delete',
  GROUP_MEMBER_LIST: 'group member list',
  GROUP_MEMBER_UPDATE: 'group member update',
  GROUP_PROFILE: 'group profile',
  GROUP_PROFILE_UPDATE: 'group profile update',
  GROUP_STATS: 'group stats',

  MESSAGE_CONVERSATION_LIST: 'message conversation list',
  MESSAGE_GROUP_HISTORY_LIST: 'message group history list',
  MESSAGE_GROUP_SUBSCRIBE: 'message group subscribe',
  MESSAGE_GROUP_UNSUBSCRIBE: 'message group unsubscribe',
  MESSAGE_PRIVATE_HISTORY_LIST: 'message private history list',
  MESSAGE_PRIVATE_SUBSCRIBE: 'message private subscribe',
  MESSAGE_SEND: 'message send',
  MESSAGE_SETTING: 'message setting',
  MESSAGE_SETTING_UPDATE: 'message setting update',
  MESSAGE_UPDATE: 'message update',
  MESSAGE_UPDATE_LIST: 'message update list',

  METADATA_URL: 'metadata url',
  METADATA_URL_BLACKLIST: 'metadata url blacklist',

  NOTIFICATION_LIST: 'notification list',
  NOTIFICATION_LIST_CLEAR: 'notification list clear',

  SEARCH: 'search',

  SECURITY_LOGIN: 'security login',
  SECURITY_LOGOUT: 'security logout',
  SECURITY_TOKEN_REFRESH: 'security token refresh',

  STAGE_GROUP_ACTIVE_LIST: 'stage group active list',
  STAGE_LIST: 'stage list',

  STORE_CREDIT_BALANCE: 'store credit balance',

  // TODO: Support store when released

  SUBSCRIBER_BLOCK_ADD: 'subscriber block add',
  SUBSCRIBER_BLOCK_DELETE: 'subscriber block delete',
  SUBSCRIBER_BLOCK_LIST: 'subscriber block list',
  SUBSCRIBER_CONTACT_ADD: 'subscriber contact add',
  SUBSCRIBER_CONTACT_DELETE: 'subscriber contact delete',
  SUBSCRIBER_CONTACT_LIST: 'subscriber contact list',
  SUBSCRIBER_GROUP_EVENT_ADD: 'subscriber group event add',
  SUBSCRIBER_GROUP_EVENT_DELETE: 'subscriber group event delete',
  SUBSCRIBER_GROUP_EVENT_LIST: 'subscriber group event list',
  SUBSCRIBER_GROUP_LIST: 'subscriber group list',
  SUBSCRIBER_PROFILE: 'subscriber profile',
  SUBSCRIBER_PROFILE_UPDATE: 'subscriber profile update',
  SUBSCRIBER_SETTINGS_UPDATE: 'subscriber settings update',

  TIP_ADD: 'tip add',
  TIP_DETAIL: 'tip detail',
  TIP_GROUP_SUBSCRIBE: 'tip group subscribe',
  TIP_LEADERBOARD_GLOBAL: 'tip leaderboard global',
  TIP_LEADERBOARD_GLOBAL_SUMMARY: 'tip leaderboard global summary',
  TIP_LEADERBOARD_GROUP: 'tip leaderboard group',
  TIP_LEADERBOARD_GROUP_SUMMARY: 'tip leaderboard group summary',
  TIP_PRIVATE_SUBSCRIBE: 'tip private subscribe',
  TIP_SUMMARY: 'tip summary',

  TOPIC_PAGE_LAYOUT: 'topic page layout',
  TOPIC_PAGE_RECIPE_LIST: 'topic page recipe list'
};
