
export const GROUP_MESSAGE = 1 << 1;
export const GROUP_MESSAGE_TIPPING = 1 << 2;
export const PRIVATE_MESSAGE = 1 << 3;
export const PRIVATE_MESSAGE_TIPPING = 1 << 4;

export default {
  GROUP_MESSAGE,
  GROUP_MESSAGE_TIPPING,
  PRIVATE_MESSAGE,
  PRIVATE_MESSAGE_TIPPING
};
