
api:
  connection:
    host: https://v3-rc.palringo.com
    port: 443
    query:
      device: wjs

  avatars:
    placeholder: https://d1gymp1zkvlptp.cloudfront.net/profiles/avatars/{type}/placeholder_{lastNumOfId}.jpg

  # Default values to use within helpers
  helper:
    charm:
      statistics:
        extend: true # Extend the users statistics
      active:
        limit: 50 # The maximum active charms to fetch in a single request
      expired:
        limit: 50 # The maximum expired charms to fetch in a single request

    channel:
      # Channel Message History
      message:
        history:
          limit: 50 # The maximum messages to fetch in a single request
          chronological: true # Whether or not messages should be in chronological order
      profile:
        entities: # Which part of the profiles to request
          - base
          - extended
          - audioCounts
          - audioConfig
          - messageConfig
        subsscribe: true # Whether or not to subscribe to profile updates
      member:
        list:
          bot:
            limit: 25
            batched: true
            batchType: 'offset'
          silenced:
            limit: 25
            batched: true
            batchType: 'offset'
          regular:
            limit: 100
            batched: true
            batchType: 'offset'
          privileged:
            limit: 2500
            subscribe: true
            batchType: 'after'
    event:
      channel:
        list:
          limit: 50
      user:
        subscribe: true # Whether or not to subscribe to user group event list

    messaging:
      channel:
        previews: true # Whether or not to attach previews on message send
      private:
        previews: true # Whether or not to attach previews on message send

    notification:
      global:
        subscribe: true # Whether or not to subscribe to global notifications
      user:
        subscribe: true # Whether or not to subscribe to user notifications

    role:
      channel:
        subscribe: true # Whether or not to subscribe to channel role changes

    stage:
      request:
        list:
          subscribe: true # Whether or not to subscribe to channel stage request changes
      slot:
        list:
          subscribe: true # Whether or not to subscribe to channel stage slot changes

    tipping:
      details:
        limit: 20
      summary:
        limit: 20

    presence:
      subscribe: true # Whether or not to subscribe to user presence changes

    user:
      message:
        history:
          limit: 50 # The maximum messages to fetch in a single request
          chronological: true # Whether or not messages should be in chronological order

      profile:
        subscribe: true # Whether or not to subscribe to user profile changes
        extend: true # Whether or not to request the entire profile